---
# tasks file for TP_INI

 - name: "Rol: TP_INI - Grupo: {{ Linux_is_good }}"
   debug:
     msg: "Inicio de tareas dentro del Rol: TP_INI"

 - name: "Crear directorios en /tmp/Grupo/"
   file:
     path: "/tmp/Grupo/"
     state: directory
     owner: vagrant
     group: vagrant
     mode: '0775'

 - name: "Agrego archivo desde template"
   template:
     src: template_01.j2
     dest: /tmp/Grupo/datos.txt
